# Generated by Django 2.2 on 2019-05-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text_Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=22)),
                ('message', models.CharField(default='', max_length=500)),
                ('dt_time', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
