# Generated by Django 2.2.1 on 2019-06-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_parent_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Academic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=11)),
                ('sem', models.CharField(max_length=4)),
                ('subject', models.CharField(max_length=50)),
                ('mid1', models.CharField(max_length=3)),
                ('mid2', models.CharField(max_length=3)),
                ('internal', models.CharField(max_length=3)),
                ('external', models.CharField(max_length=3)),
            ],
        ),
    ]
