# Generated by Django 2.2.1 on 2019-06-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_discipline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counselor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='hod',
            name='id',
        ),
        migrations.AlterField(
            model_name='counselor',
            name='counselor_id',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hod',
            name='hod_id',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
